resolver: lts-14.14

ghc-options: {"$locals": -ddump-to-file -ddump-hi}


extra-deps:
  # --- Missing from Stackage --- #
  - generic-lens-1.2.0.1
  - paths-0.2.0.0
  - streaming-events-1.0.0
  - strict-tuple-0.1.3

  # --- Transitive Chainweb Dependencies --- #
  - QuickCheck-GenT-0.2.2
  - bloomfilter-2.0.1.0
  - digraph-0.1.0.2
  - fake-0.1.1.2
  - loglevel-0.1.0.0
  - merkle-log-0.1.0.0
  - tls-1.5.2
  - yet-another-logger-0.3.1
  - OpenCL-1.0.3.4@sha256:ef90f955632749353251887ce66357c5ed8e98e8b437ff91ce406ae9187f3953,2590

  # --- Transitive Pact Dependencies --- #
  - ed25519-donna-0.1.1
  - sbv-8.2
  - trifecta-2.1
