on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Upload Release Artifact

jobs:
  build:
    name: Upload Release Asset
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]

    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Read Caches
        uses: actions/cache@v1
        with:
          path: dist-newstyle
          key: ${{ runner.OS }}-dist-${{ hashFiles('.ghc.environment.x86_64-linux-8.6.5') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Set up Haskell
        uses: actions/setup-haskell@v1
        with:
          ghc-version: '8.6.5'
          cabal-version: '3.0'

      - name: Install dependencies
        run: |
          sudo apt-get install -y ocl-icd-* opencl-headers
          cabal update
          cabal install --only-dependencies

      - name: Build
        run: |
          cabal configure
          cabal build

      - name: Create Artifact
        run: |
          cabal install --installdir=./
          zip -j kda-miner-${{ github.ref }}-${{ runner.OS }}.zip kda-miner README.md

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./my-artifact.zip
          asset_name: my-artifact.zip
          asset_content_type: application/zip
