name: Haskell CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]

    steps:
    - name: Set up Haskell
      uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.6.5'
        cabal-version: '3.0'

    - name: Ubuntu Dependencies
      run: | 
        sudo apt-get install -y opencl-headers
        sudo apt-get install -y ocl-icd-* 

    - name: Cabal Dependencies
      run: |
        rm -rf /home/runner/.cabal
        cabal update
        cabal install --only-dependencies

    - name: Build
      run: |
        cabal configure
        cabal build

