name: Haskell Ubuntu

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]

    - name: Checkout code
      uses: actions/checkout@master
    
    steps:
    - name: Set up Haskell
      uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.6.5'
        cabal-version: '3.0'
    
    # Ugly hack. This will always cache-miss. See Load Artifact below
    - name: Prep Store Bin
      id: cache-bin
      uses: actions/cache@v1
      with:
        path: ./out
        key: ${{ matrix.os }}-bin-${{ github.sha }}


    - name: Ubuntu Dependencies
      if: steps.cache-bin.outputs.cache-hit != 'true'
      run: | 
        sudo apt-get install -y opencl-headers
        sudo apt-get install -y ocl-icd-* 

    - name: Cabal Cache
      if: steps.cache-bin.outputs.cache-hit != 'true'
      uses: actions/cache@v1
      with:
        path: /home/runner/.cabal
        key: ${{ matrix.os }}-cabal
    
    - name: Build Cache
      if: steps.cache-bin.outputs.cache-hit != 'true'
      uses: actions/cache@v1
      with:
        path: dist-newstyle
        key: ${{ matrix.os }}-dist-newstyle

    - name: Cabal Build
      if: steps.cache-bin.outputs.cache-hit != 'true'
      run: |
        cabal update
        cabal configure
        cabal build
        mkdir -p ./out
        rm -rf ./out/*
        cabal install --installdir=./out/
        cp --remove-destination $(readlink ./out/kda-miner) ./out/kda-miner


  release:
    name: Create Github Release
    if: contains(github.ref, 'tags/v')
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Get version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.VERSION }}        
        release_name: Release ${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false

    - name: Output Release URL File
      run: echo "${{ steps.create_release.outputs.upload_url }}" > release_url.txt

    - name: Save Release URL File for publish
      uses: actions/upload-artifact@v1
      with:
        name: release_url
        path: release_url.txt

  publish:
    if: contains(github.ref, 'tags/v')
    needs: [build, release]
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        os: [ubuntu-16.04, ubuntu-18.04]
    steps:
    - uses: actions/checkout@v1

    - name: Get version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Set up Haskell
      uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.6.5'
        cabal-version: '3.0'

    # Ugly hack. See ugly hack above.
    - name: Load Bin
      uses: actions/cache@v1
      with:
        path: ./out
        key: ${{ matrix.os }}-bin-${{ github.sha }}

    - name: LDD Info
      run: |
        echo ""
        ldd --version
        echo ""
        ldd -r -v ./out/kda-miner

        strip ./out/kda-miner

    - name: Package Artifact 
      run: |
        zip -j kda-miner-${{ matrix.os }}-${TAG_REF_NAME##*/v}.zip ./out/kda-miner README.md LICENSE
      env:
        TAG_REF_NAME: ${{ github.ref }}

    - name: Load Release URL File from release job
      uses: actions/download-artifact@v1
      with:
        name: release_url

    - name: Get Release File Name & Upload URL
      id: get_release_info
      run: |
        ls -al
        echo ::set-output name=file_name::kda-miner-${{ matrix.os }}-${TAG_REF_NAME##*/v}
        value=`cat release_url/release_url.txt`
        echo ::set-output name=upload_url::$value
      env:
        TAG_REF_NAME: ${{ github.ref }}
        REPOSITORY_NAME: ${{ github.repository }}

    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: ./${{ steps.get_release_info.outputs.file_name }}.zip
        asset_name: ${{ steps.get_release_info.outputs.file_name }}.zip
        asset_content_type: application/zip
