name: Haskell CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Read Caches
      uses: actions/cache@v1
      with:
        path: dist-newstyle
        key: ${{ runner.OS }}-dist-${{ hashFiles('.ghc.environment.x86_64-linux-8.6.5' }}
        restore-keys: |
          ${{ runner.OS }}-build-${{ env.cache-name }}
          ${{ runner.OS }}-build-
          ${{ runner.OS }}-

    - name: Set up Haskell
      uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.6.5'
        cabal-version: '3.0'

    - name: Install dependencies
      run: |
        sudo apt-get install -y ocl-icd-* opencl-headers
        cabal update
        cabal install --only-dependencies

    - name: Build
      run: |
        cabal configure
        cabal build

